/**
 * This file generates the API manifest and OpenAPI document from both flat
 * route files and module-oriented route directories.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { listFilesRecursive, pathExists } from './fs.js';
import { apiPathFromRelativeFile, relPosix, withoutExt } from './paths.js';

type GenerateApiOptions = {
  rootDir: string;
  srcDir?: string;
  apiDir?: string;
  outDir?: string;
};

type RouteEntry = {
  importPath: string;
  path: string;
};

type RouteRoot = {
  dir: string;
  mapFile: (absFile: string) => RouteEntry | undefined;
};

function toImportName(i: number): string {
  return `route_${i}`;
}

function normalizeRouteImportPath(prefix: string, relFile: string): string {
  return `${prefix}/${withoutExt(relFile)}.js`;
}

function isRouteSourceFile(absFile: string): boolean {
  if (absFile.endsWith('.d.ts')) return false;
  if (absFile.endsWith('.test.ts') || absFile.endsWith('.spec.ts')) return false;
  return true;
}

async function collectRouteEntries(roots: RouteRoot[]): Promise<RouteEntry[]> {
  const entries: RouteEntry[] = [];
  for (const root of roots) {
    if (!(await pathExists(root.dir))) continue;
    const files = await listFilesRecursive(root.dir, { ext: ['.ts', '.tsx'], ignoreDirNames: ['__tests__'] });
    for (const absFile of files) {
      if (!isRouteSourceFile(absFile)) continue;
      const entry = root.mapFile(absFile);
      if (entry) entries.push(entry);
    }
  }
  return entries.sort((left, right) => left.path.localeCompare(right.path) || left.importPath.localeCompare(right.importPath));
}

function renderGenerated(entries: RouteEntry[]): string {
  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * This file is auto-generated by the Rasono CLI from API route modules.');
  lines.push(' */');
  lines.push("import { buildOpenApiDocument, installApiRoute, type ApiRoute } from '@rasono/app';");
  lines.push('');
  for (let i = 0; i < entries.length; i += 1) {
    lines.push(`import ${toImportName(i)} from '${entries[i]!.importPath}';`);
  }
  if (entries.length > 0) lines.push('');
  lines.push('export type GeneratedRoute = {');
  lines.push('  file: string;');
  lines.push('  path: string;');
  lines.push('  route: ApiRoute;');
  lines.push('};');
  lines.push('');
  lines.push('export const generatedRoutes: GeneratedRoute[] = [');
  for (let i = 0; i < entries.length; i += 1) {
    const entry = entries[i]!;
    const r = toImportName(i);
    lines.push(`  { file: '${entry.importPath}', path: '${entry.path}', route: ${r} },`);
  }
  lines.push('];');
  lines.push('');
  lines.push('export function installGeneratedApi(app: any): void {');
  lines.push('  for (const entry of generatedRoutes) installApiRoute(app, entry.path, entry.route);');
  lines.push('}');
  lines.push('');
  lines.push('export function getOpenApiDocument(info: { title: string; version: string }): any {');
  lines.push('  return buildOpenApiDocument(generatedRoutes, info);');
  lines.push('}');
  lines.push('');
  lines.push('export function installGeneratedDocs(app: any, info: { title: string; version: string }, options?: { docPath?: string }): void {');
  lines.push("  const docPath = options?.docPath ?? '/doc';");
  lines.push('  app.get(docPath, (c: any) => c.json(getOpenApiDocument(info)));');
  lines.push('}');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

export async function generateApi(options: GenerateApiOptions): Promise<{ outFile: string; count: number }> {
  const srcDir = resolve(options.rootDir, options.srcDir ?? 'src');
  const apiDir = resolve(srcDir, options.apiDir ?? 'api');
  const modulesDir = resolve(srcDir, 'modules');
  const outDir = resolve(srcDir, options.outDir ?? '.rasono');
  const outFile = resolve(outDir, 'api.generated.ts');

  if (!(await pathExists(apiDir)) && !(await pathExists(modulesDir))) {
    await mkdir(outDir, { recursive: true });
    await writeFile(outFile, renderGenerated([]), 'utf8');
    return { outFile, count: 0 };
  }

  const entries = await collectRouteEntries([
    {
      dir: apiDir,
      mapFile: (absFile) => {
        const relFromApi = relPosix(apiDir, absFile);
        const routeRel = withoutExt(relFromApi);
        return {
          importPath: normalizeRouteImportPath('../api', relFromApi),
          path: apiPathFromRelativeFile(routeRel),
        };
      },
    },
    {
      dir: modulesDir,
      mapFile: (absFile) => {
        const relFromModules = withoutExt(relPosix(modulesDir, absFile));
        const parts = relFromModules.split('/').filter(Boolean);
        const apiIndex = parts.indexOf('api');
        if (apiIndex < 1) return undefined;
        const routeRel = [...parts.slice(0, apiIndex), ...parts.slice(apiIndex + 1)].join('/');
        if (!routeRel) return undefined;
        return {
          importPath: normalizeRouteImportPath('../modules', `${relFromModules}.ts`),
          path: apiPathFromRelativeFile(routeRel),
        };
      },
    },
  ]);

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, renderGenerated(entries), 'utf8');
  return { outFile, count: entries.length };
}
