/**
 * This file generates a framework-agnostic RPC client from discovered API
 * routes, including module-based route directories.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { analyzeRouteFile } from './analyzeRoute.js';
import { listFilesRecursive, pathExists } from './fs.js';
import { apiPathFromRelativeFile, relPosix, withoutExt } from './paths.js';

type GenerateRpcOptions = {
  rootDir: string;
  srcDir?: string;
  outDir?: string;
  apiRootDir?: string;
  apiSrcDir?: string;
  apiDir?: string;
};

type RpcEntry = {
  accessor: string[];
  method: string;
  path: string;
};

type RpcTreeNode = {
  children: Map<string, RpcTreeNode>;
  entry?: RpcEntry;
};

type RpcRoot = {
  dir: string;
  mapFile: (absFile: string) => { filePath: string; routeRel: string } | undefined;
};

function toAccessor(relNoExt: string): string[] {
  const segments = relNoExt.split('/').filter(Boolean);
  return segments.map((segment) => {
    const inner = segment.replace(/^\[(\.\.\.)?/, '').replace(/\]$/, '');
    const normalized = inner.replace(/[^a-zA-Z0-9]+/g, '_');
    if (!normalized) return 'route';
    return /^[0-9]/.test(normalized) ? `r_${normalized}` : normalized;
  });
}

function isRouteSourceFile(absFile: string): boolean {
  if (absFile.endsWith('.d.ts')) return false;
  if (absFile.endsWith('.test.ts') || absFile.endsWith('.spec.ts')) return false;
  return true;
}

async function collectRpcEntries(roots: RpcRoot[]): Promise<RpcEntry[]> {
  const entries: RpcEntry[] = [];
  for (const root of roots) {
    if (!(await pathExists(root.dir))) continue;
    const files = await listFilesRecursive(root.dir, { ext: ['.ts', '.tsx'], ignoreDirNames: ['__tests__'] });
    for (const absFile of files) {
      if (!isRouteSourceFile(absFile)) continue;
      const mapped = root.mapFile(absFile);
      if (!mapped) continue;
      const analysis = await analyzeRouteFile(mapped.filePath);
      entries.push({
        accessor: toAccessor(mapped.routeRel),
        method: analysis.method,
        path: apiPathFromRelativeFile(mapped.routeRel),
      });
    }
  }
  return entries.sort((left, right) => left.path.localeCompare(right.path) || left.method.localeCompare(right.method));
}

function insertTree(root: RpcTreeNode, entry: RpcEntry): void {
  let node = root;
  for (const segment of entry.accessor) {
    let next = node.children.get(segment);
    if (!next) {
      next = { children: new Map() };
      node.children.set(segment, next);
    }
    node = next;
  }
  node.entry = entry;
}

function renderNode(node: RpcTreeNode, indent: string): string[] {
  const lines: string[] = [];
  const keys = Array.from(node.children.keys()).sort();
  for (const key of keys) {
    const child = node.children.get(key)!;
    if (child.entry) {
      const entry = child.entry;
      lines.push(`${indent}${key}: {`);
      lines.push(
        `${indent}  ${entry.method}: (input?: { query?: Record<string, string | number | boolean | null | undefined>; json?: unknown; headers?: Record<string, string> }) => api.request({ method: '${entry.method.toUpperCase()}', path: '${entry.path}', query: input?.query, json: input?.json, headers: input?.headers }),`,
      );
      lines.push(`${indent}},`);
      continue;
    }
    lines.push(`${indent}${key}: {`);
    lines.push(...renderNode(child, `${indent}  `));
    lines.push(`${indent}},`);
  }
  return lines;
}

function renderGenerated(entries: RpcEntry[]): string {
  const root: RpcTreeNode = { children: new Map() };
  for (const entry of entries) insertTree(root, entry);

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * This file is auto-generated by the Rasono CLI from API route modules.');
  lines.push(' */');
  if (entries.length === 0) {
    lines.push('export type ApiClientOptions = {');
    lines.push('  baseUrl: string;');
    lines.push('  fetch?: typeof fetch;');
    lines.push('  headers?: Record<string, string>;');
    lines.push('};');
    lines.push('');
    lines.push('export function createGeneratedRpcClient(_options: ApiClientOptions) {');
    lines.push('  return {};');
    lines.push('}');
    lines.push('');
    return `${lines.join('\n')}\n`;
  }
  lines.push("import { createApiClient, type ApiClientOptions } from '@rasono/web-core';");
  lines.push('');
  lines.push('export function createGeneratedRpcClient(options: ApiClientOptions) {');
  lines.push('  const api = createApiClient(options);');
  lines.push('  return {');
  lines.push(...renderNode(root, '    '));
  lines.push('  };');
  lines.push('}');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

export async function generateRpc(options: GenerateRpcOptions): Promise<{ outFile: string; count: number }> {
  const srcDir = resolve(options.rootDir, options.srcDir ?? 'src');
  const outDir = resolve(srcDir, options.outDir ?? '.rasono');
  const outFile = resolve(outDir, 'rpc.generated.ts');
  const apiRootDir = resolve(options.rootDir, options.apiRootDir ?? '../api');
  const apiSrcDir = resolve(apiRootDir, options.apiSrcDir ?? 'src');
  const apiDir = resolve(apiSrcDir, options.apiDir ?? 'api');
  const modulesDir = resolve(apiSrcDir, 'modules');

  if (!(await pathExists(apiDir)) && !(await pathExists(modulesDir))) {
    await mkdir(outDir, { recursive: true });
    await writeFile(outFile, renderGenerated([]), 'utf8');
    return { outFile, count: 0 };
  }

  const entries = await collectRpcEntries([
    {
      dir: apiDir,
      mapFile: (absFile) => ({
        filePath: absFile,
        routeRel: withoutExt(relPosix(apiDir, absFile)),
      }),
    },
    {
      dir: modulesDir,
      mapFile: (absFile) => {
        const relFromModules = withoutExt(relPosix(modulesDir, absFile));
        const parts = relFromModules.split('/').filter(Boolean);
        const apiIndex = parts.indexOf('api');
        if (apiIndex < 1) return undefined;
        const routeRel = [...parts.slice(0, apiIndex), ...parts.slice(apiIndex + 1)].join('/');
        if (!routeRel) return undefined;
        return { filePath: absFile, routeRel };
      },
    },
  ]);

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, renderGenerated(entries), 'utf8');
  return { outFile, count: entries.length };
}
